FROM ibmcom/ace
USER aceuser
ARG BAR_FILE=bars/RBS_AccountBalanceDetails_v1*.bar 
COPY ${BAR_FILE} /home/aceuser/initial-config/bars/
USER root
RUN chown -R aceuser:mqbrkrs $ODBCINI && chmod 755 $ODBCINI
USER aceuser
