FROM ibmcom/ace
USER aceuser
COPY /root/githubactions/actions-runner/_work/CAT_A_01/CAT_A_01/bars/RBS_AccountBalanceDetails_v1*.bar /home/aceuser/initial-config/bars/
USER root
RUN chown -R aceuser:mqbrkrs $ODBCINI && chmod 755 $ODBCINI
USER aceuser
